language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  slack: teamtrillium:P5f5xEQfrZbhn0NeFiValIEA

cache:
  directories:
  - .autoconf
  - $HOME/.m2

after_success:
  - mvn clean test jacoco:report coveralls:report
