author: LordSaad44
authors: [ VortexSeven, Turbotailz, samczsun, hintss ]
description: The Premium Essentials.
main: net.gettrillium.trillium.Trillium
name: Trillium
version: 0.3.0
softDepend: [Vault]
